# Extra autostart processes
# exec-once = uwsm-app -- my-service

# Animated Gundam wallpaper (mpvpaper on both monitors)
exec-once = bash -c "sleep 2 && pkill -x swaybg && uwsm-app -- mpvpaper -o 'no-audio --loop=inf --hwdec=auto' HDMI-A-1 /home/jorge/Videos/Wallpapers/gundam-white.mp4 & uwsm-app -- mpvpaper -o 'no-audio --loop=inf --hwdec=auto' DP-1 /home/jorge/Videos/Wallpapers/gundam-white.mp4"
